# Generated by Django 3.1.6 on 2021-03-23 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(max_length=254)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField \
                    (auto_now_add=True, verbose_name='post_created_date')),
                ('status', models.IntegerField(choices=[(0, 'Draft'),
                                                        (1, 'Publish')], \
                                                            default=0)),
                ('author', models.ForeignKey \
                    (on_delete=django.db.models.deletion.CASCADE,
                     related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('article_id', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models \
                                                 .deletion.SET_NULL, \
                                                 to='blog.blogpost', \
                                                 verbose_name='image_article_id')),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=50)),
                ('blog_comment', models.TextField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True,
                                                    verbose_name='comment_created_date')),
                ('article_id', models.ForeignKey(blank=True,
                                                 null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blog.blogpost')),
                ('user_id', models.ForeignKey(blank=True,
                                              null=True,
                                              on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
