# Generated by Django 3.1.6 on 2021-02-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0003_auto_20210219_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=
                                    django.db.models.deletion.SET_NULL,
                                    related_name='orders',
                                    to='profiles.userprofile'),
        ),
    ]
